[package]
name = "test-server"
version = "0.1.0"
authors = ["bryantheastronaut <gilbraith.bryan@gmail.com>"]

[dependencies]
nickel = "0.10.1"
rustc-serialize = "0.3.24"
jwt = "0.4.0"
rust-crypto = "0.2.36"
bson = "0.11.0"
hyper = "0.11.14"